<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb5b1e13849bc602b5301f102133d145d
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Wp\\Easyrestapi\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Wp\\Easyrestapi\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb5b1e13849bc602b5301f102133d145d::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb5b1e13849bc602b5301f102133d145d::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb5b1e13849bc602b5301f102133d145d::$classMap;

        }, null, ClassLoader::class);
    }
}
